name: Rust

on:
  workflow_dispatch: # makes it only run when I tell it to

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v6
    - name: Install linux stuff
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev

    - name: Build
      run: cargo build --release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: midi-bounce-${{ matrix.os }}
        path: |
          target/release/midi-bounce.exe
          target/release/midi-bounce